---
services:
  bullseye:
    build:
      context: ..
      dockerfile: docker/debian/Dockerfile
      args:
        OS: debian:bullseye
  bookworm:
    build:
      context: ..
      dockerfile: docker/debian/Dockerfile
      args:
        OS: debian:bookworm
  trixie:
    build:
      context: ..
      dockerfile: docker/debian/Dockerfile
      args:
        OS: debian:trixie
  fedora:
    build:
      context: ..
      dockerfile: docker/rpm/Dockerfile
      args:
        OS: fedora:latest
  rockylinux10:
    build:
      context: ..
      dockerfile: docker/rpm/Dockerfile
      args:
        OS: rockylinux/rockylinux:10
