name: CI validation (Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        variant: [server, client]

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-env
        with:
          profile: default

      - uses: ./.github/actions/select-compiler
        with:
          compiler: gcc

      - uses: ./.github/actions/configure-xymon
        with:
          variant: ${{ matrix.variant }}
          profile: default

      - uses: ./.github/actions/build-xymon

